# Generated by Django 4.2 on 2023-04-08 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='day',
        ),
        migrations.CreateModel(
            name='SplitWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=20)),
                ('workout', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='overload.workout')),
            ],
        ),
    ]
