# Generated by Django 4.2 on 2023-08-14 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutexercise',
            name='sets',
        ),
        migrations.AddField(
            model_name='set',
            name='workout_exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='overload.workoutexercise'),
            preserve_default=False,
        ),
    ]
