# Generated by Django 4.2.7 on 2023-11-28 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overload', '0002_remove_workoutexercise_sets_set_workout_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='workout_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='overload.workoutexercise'),
        ),
    ]
