# Generated by Django 4.2 on 2023-04-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overload', '0002_remove_workout_day_splitworkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('C', 'Compound'), ('I', 'Isolation')], default='I', max_length=1),
        ),
    ]
