# Generated by Django 4.2 on 2023-04-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overload', '0003_exercise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
