# Generated by Django 4.2.7 on 2023-11-29 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overload', '0003_alter_set_workout_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='personal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='overload.profile'),
        ),
    ]
