# Generated by Django 4.2.7 on 2023-11-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overload', '0004_exercise_personal_exercise_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
