# Generated by Django 4.2.7 on 2023-12-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overload', '0005_alter_profile_height_alter_profile_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
